AWSTemplateFormatVersion: '2010-09-09'
Description: "ECR Create For Batch, Front."

Parameters:
  SystemOnlineTime:
    Type: String
  ActiveTargetGroupArn:
    Type: String

Resources:
  # ------------------------------------------------------------#
  #  ALB Front用
  # ------------------------------------------------------------#
  InternetAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Sub "alb-cmn-front"
      Scheme: 'internal'
      Subnets:
        - 'subnet-083b00b754ba3beaa'
        - 'subnet-01ad44f3b349f00e1'
        - 'subnet-0eb161cab7a96641d'
      SecurityGroups:
        - 'sg-08387e4a7f0f6e2ca'


  # ------------------------------------------------------------#
  #  ALB Listener for Prod(Blue).
  # ------------------------------------------------------------#
  AlbListenerProdTraffic:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AlbTargetGroupBlue
                Weight: 1
      LoadBalancerArn: !Ref InternetAlb
      Port: 80
      Protocol: HTTP

  # ------------------------------------------------------------#
  #  ALB Listener for Prod(Blue).
  # ------------------------------------------------------------#
  AlbListenerProdTrafficMain:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ActiveTargetGroupArn
                Weight: 1
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
              Values:
                - '*'
      ListenerArn: !Ref AlbListenerProdTraffic
      Priority: 10

  # ------------------------------------------------------------#
  #  ALB Listener rule (service out) for Prod(Blue).
  # ------------------------------------------------------------#
  AlbListenerProdTrafficListenerServiceOut:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/html
            MessageBody: !Sub |
                  <!DOCTYPE html>
                  <html>
                  <head>
                  <meta charset="utf-8">
                  <title>Maintenance</title>
                  <style>
                    html{
                      margin: 0;
                      padding: 0;
                      text-align: center;
                      height: 100%;
                    }
                    body{
                      position: relative;
                      height: 100%;
                      background: #eee;
                    }
                    div{
                      position: absolute;
                      left: 50%;
                      top: 30%;
                      margin-left: -300px;
                      width: 600px;
                      border: 2px solid #666;
                      padding: 64px 32px;
                      box-sizing: border-box;
                      background: #fff;
                      text-align: center;
                    }
                    .message{
                      font-size: 34px;
                      margin-bottom: 24px;
                      font-weight: bold;
                    }
                    .date{
                      color: #fff;
                      padding: 8px;
                      background: #cc0000;
                      width: 90%;
                      margin: 0 auto 16px;
                    }
                  </style>
                  </head>
                  <body>
                  <div>
                    <p class="message">ただいまサービス利用時間外です</p>
                    <p class="date">【サービス利用時間】${SystemOnlineTime}</p>
                    <p>ご利用の皆様にはご迷惑をおかけし、大変申し訳ございません。<br>
                    利用開始時間までしばらくお待ちください。</p>
                  </div>
                  </body>
                  </html>
            StatusCode: 503
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
              Values:
                - '*'
      ListenerArn: !Ref AlbListenerProdTraffic
      Priority: 15

  # ------------------------------------------------------------#
  #  ALB Target Group for Blue.
  # ------------------------------------------------------------#
  AlbTargetGroupBlue:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: 'vpc-0b7100f164a6071dd'
      Name: !Sub "cmn-tg-test-front-blue"
      Protocol: HTTP
      Port: 80
      TargetType: ip
      HealthCheckPath: /
      HealthCheckPort: '80'
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200'

  AlbTargetGroupGreen:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: 'vpc-0b7100f164a6071dd'
      Name: !Sub "cmn-tg-test-front-green"
      Protocol: HTTP
      Port: 80
      TargetType: ip
      HealthCheckPath: /
      HealthCheckPort: '80'
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200'

