AWSTemplateFormatVersion: '2010-09-09'
Description: "ECR Create For Batch, Front."

Parameters: ###########################################
  # システム共通（全ドメインで共通）※CMNのみのconfに記載
  ###########################################
  CompanyId:
    Type: String
  SystemId:
    Type: String
  EnvId:
    Type: String
  EnvName:
    Type: String
  SystemName:
    Type: String
  ###########################################
  # ドメイン固有
  ###########################################
  SubSystemId:
    Type: String
  CicdRepository:
    Type: String



Conditions:
  #環境（EnvName）がDEVの場合　　：true
  isEnvDev:
    !Equals [!Ref EnvName, "DEV"]

Resources:
  # ---------------------------------------------------------
  # Step Functions
  # ---------------------------------------------------------
  ExecS3CopyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/statemachines/exec-s3copy.asl.json
      DefinitionSubstitutions:
        PriLSubnet1: {'Fn::ImportValue': !Sub '${EnvId}-cmn-PriLSubnet1'}
        PriLSubnet2: {'Fn::ImportValue': !Sub '${EnvId}-cmn-PriLSubnet2'}
        PriMSubnet1: {'Fn::ImportValue': !Sub '${EnvId}-cmn-PriMSubnet1'}
        PriMSubnet2: {'Fn::ImportValue': !Sub '${EnvId}-cmn-PriMSubnet2'}
        S3CopyEcsClusterArn: !GetAtt ScriptRunnerEcsCluster.Arn
        S3CopyEcsTaskDefinitionArn: !Ref ExecS3CopyEcsTaskDefinition
        #SG Import名要修正
        S3CopyEcsSecurityGroupId: {'Fn::ImportValue': !Sub '${EnvId}-${SubSystemId}-SG-BatchEcsSecurityGroupId'}
        S3CopyEcsContainerName: !Sub "${SubSystemId}-ecstask-${EnvId}-batch-exec-s3copy-ecs-container"
      Events:
        HourlySchedule:
          Type: Schedule
          Properties:
            Description: Every hour
            Enabled: False  #  Set to "True" to enable
            # See: https://docs.aws.amazon.com/ja_jp/eventbridge/latest/userguide/eb-create-rule-schedule.html
            Schedule: "cron(0 * * * ? *)"
      Role: {'Fn::ImportValue': !Sub '${EnvId}-${SubSystemId}-IamRole-BatchScriptRunnerStateMachineRoleArn'}
      Tags:
        Name: "Execs3copyStateMachine"
        Env: !Ref EnvName
        System: !Ref SystemId
        SystemName: !Ref SystemName
        SubSystemId: !Ref SubSystemId
        CicdRepository: !Ref CicdRepository
          
  
  # ---------------------------------------------------------
  # ECS Fargate(バッチで利用しない可能性あり。)
  # ---------------------------------------------------------
  ScriptRunnerEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${SubSystemId}-ecscluster-${EnvId}-batch"
      Tags:
        - Key: "Name"
          Value: !Sub "${SubSystemId}-ecscluster-${EnvId}-batch"
        - Key: "Env"
          Value: !Ref EnvName
        - Key: "System"
          Value: !Ref SystemId
        - Key: "SystemName"
          Value: !Ref SystemName
        - Key: "SubSystemId"
          Value: !Ref SubSystemId
        - Key: "CicdRepository"
          Value: !Ref CicdRepository

  ExecS3CopyEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub "${SubSystemId}-ecstask-${EnvId}-batch-exec-s3copy-ecs-container"
          Image:
            !Join
              - ''
              - - {'Fn::ImportValue': !Sub '${EnvId}-${SubSystemId}-ECR-BatchScriptRunnerEcrRepositoryUri'}
                - ':latest'
          Cpu: 2048
          MemoryReservation: 4096
          ReadonlyRootFilesystem: true
          EntryPoint:
            - "/bin/bash"
            - "-c"
          Command:
            - "bash -eux scripts/exec-s3copy.sh"
          Environment:
            - Name: "ENV_SRC_BUCKET"
              Value: "_PLACEHOLDER_"
            - Name: "ENV_SRC_PATH"
              Value: "_PLACEHOLDER_"
            - Name: "ENV_SRC_FILE"
              Value: "_PLACEHOLDER_"
            - Name: "ENV_DST_BUCKET"
              Value: "_PLACEHOLDER_"
            - Name: "ENV_DST_PATH"
              Value: "_PLACEHOLDER_"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ExecS3CopyEcsLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Family: !Sub "${SubSystemId}-ecstask-${EnvId}-batch-exec-s3copy"
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      #Role Import名要修正
      TaskRoleArn: {'Fn::ImportValue': !Sub '${EnvId}-${SubSystemId}-IamRole-BatchScriptRunnerEcsTaskRoleArn'}
      ExecutionRoleArn: {'Fn::ImportValue': !Sub '${EnvId}-${SubSystemId}-IamRole-BatchScriptRunnerEcsTaskExecutionRoleArn'}
      Tags:
        - Key: "Name"
          Value: !Sub "${SubSystemId}-ecstask-${EnvId}-batch-exec-s3copy"
        - Key: "Env"
          Value: !Ref EnvName
        - Key: "System"
          Value: !Ref SystemId
        - Key: "SystemName"
          Value: !Ref SystemName
        - Key: "SubSystemId"
          Value: !Ref SubSystemId
        - Key: "CicdRepository"
          Value: !Ref CicdRepository



  # ---------------------------------------------------------
  # CloudWatch Logs
  # ---------------------------------------------------------
  ExecS3CopyEcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${SystemId}/${SubSystemId}/${EnvId}/ecs/batch-exec-s3copy"
      # Set 13 months
      RetentionInDays: 400
      Tags:
        - Key: "Name"
          Value: !Sub "${SystemId}/${SubSystemId}/${EnvId}/ecs/batch-exec-s3copy"
        - Key: "Env"
          Value: !Ref EnvName
        - Key: "System"
          Value: !Ref SystemId
        - Key: "SystemName"
          Value: !Ref SystemName
        - Key: "SubSystemId"
          Value: !Ref SubSystemId
        - Key: "CicdRepository"
          Value: !Ref CicdRepository